# Generated by Django 2.0.13 on 2019-12-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
